### ISSUE TITLE
process of expired name

### ISSUE THREAD

**Issue by bettybao1209** [neo-project/non-native-contracts#1]
So do we remove the deletion logic of the expired date? Is it possible to provide Storage.FindRange method to find items in certain range?

**Comment by erikzhang** [comment]
The problem is when the logic is executed?

**Comment by bettybao1209** [comment]
The time we check the name is expired in the way of lazy deletion?

**Comment by erikzhang** [comment]
Can you clarify that in which method?

**Comment by bettybao1209** [comment]
How about we check if the `Runtime.Time >= Expiration` is true, we delete the name token and throw the exception instead of the `EnsureNotExpired` method?

**Comment by bettybao1209** [comment]
Sorry, I forgot the permission control. 

> How about we check if the `Runtime.Time >= Expiration` is true, we delete the name token and throw the exception instead of the `EnsureNotExpired` method?

**Comment by bettybao1209** [comment]
So is it possible to provide Storage.FindRange method?

**Comment by erikzhang** [comment]
> So is it possible to provide Storage.FindRange method?

As I've said, the problem is when to execute the logic.

**Comment by bettybao1209** [comment]
It is for other custom contracts.

**Comment by erikzhang** [comment]
It is easy to implement `FindRange` with `Find` in a contract.

**Comment by bettybao1209** [comment]
Get it.
